---
- name: ensure global bash configuration is set
  copy:
    src: global.sh
    dest: /etc/profile.d/global.sh
    owner: root
    group: root
    mode: 0644
  tags: profile

- name: copy .bash_profile to target
  copy:
    src: bash_profile
    dest: /home/lupin/.bash_profile
    owner: lupin
    group: lupin
    mode: 0644
  tags: profile
