---
- name: be sure ntpd is installed
  yum:
    name: ntp
    state: installed
  tags: ntpd

- name: be sure ntpd is running and enabled
  systemd:
    name: ntpd
    state: started
    enabled: yes
  tags: ntpd
