---
- name: ensure max. kernels of 3
  lineinfile:
    dest: /etc/yum.conf
    regexp: "^installonly_limit"
    line: "installonly_limit=3"
    state: present
  tags: base

- name: ensure needed base packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_packages }}"
  tags: base

- name: ensure unused base packages are removed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ remove_packages }}"
  tags: base

- include_role:
    name: sshd

- include_role:
    name: firewalld

- include_role:
    name: ntpd
